name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: myrepo111
        password: myrepo111

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: myrepo111/wisecow:latest

    - name: Log out from Docker Hub
      run: docker logout

    - name: Deploy to Kubernetes
      uses: docker://bitnami/kubectl:latest
      with:
        args: |
          kubectl config set-cluster my-cluster --server=https://<YOUR_CLUSTER_ENDPOINT> --certificate-authority=<CA_CERT>
          kubectl config set-credentials my-user --token=<YOUR_BEARER_TOKEN>
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context
          kubectl set image deployment/my-deployment my-container=myrepo111/wisecow:latest
          kubectl rollout status deployment/my-deployment
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
